### ISSUE TITLE
[Feature request] Add upgrades to weapon cards

### ISSUE THREAD

**Issue by el-hackerino** [maduck/GoWDiscordTeamBot#5]
Weapon cards should include the upgrades you unlock using ingots.

**Comment by maduck** [comment]
this has been voted down before. can do it, but not with first priority.

**Comment by el-hackerino** [comment]
That would be cool since some upgrades are very relevant and get discussed sometimes. Several players in my guild wondered about it.

**Comment by maduck** [comment]
ok, we got it a little push, together with class traits. will be coming soon.

**Comment by maduck** [comment]
done.
